### ISSUE TITLE
is the slack channel still open?

### ISSUE THREAD

**Issue by OlafEichstaedt** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#105]
in the introduction, there is "register for slack", but the link leads to a 404 error ...

**Comment by mbrodala** [comment]
Do you mean this one?

![image](https://user-images.githubusercontent.com/5037116/95050312-9b72b800-06eb-11eb-9f0a-d7472e213825.png)

This points at https://my.typo3.org/about-mytypo3org/slack/ which redirects me to a login screen just fine.

What do you see instead?

**Comment by sypets** [comment]
To register for Slack, you need a https://my.typo3.org account. Get that first and you should then also see a way to register for Slack in the menu. 

You can see this information on the start page https://my.typo3.org:

![image](https://user-images.githubusercontent.com/13206455/95051244-2c965e80-06ed-11eb-949e-89a18c7c0112.png)

The question is, where should we link to for Slack registration? 

1. I guess we could just link to https://my.typo3.org. 

2. Or we could link to the TYPO3 Documentation Team page: https://typo3.org/community/teams/documentation

I think the second is a better option because the main communication channel may change. It has changed before where we had to replace all the texts pointing to the mailing list (which still exist in some places).

**Comment by OlafEichstaedt** [comment]
I did step 1 first .... but apparently the second step did not know about it or missed a refresh.

Instead of a 404 page, it would probably be better to see something like "register first or refresh your browser" ...

**Comment by sypets** [comment]
> I did step 1 first
What do you mean with step 1?

Did it work for you? Do you still need help?

Or are you just reporting this to let us know something is not working?

If it worked for you, you can report problems here:

* issues for my.typo3.org on https://gitlab.typo3.org/t3o/my/-/issues. (To do that,  you need a my.typo3.org account.)
* There may be a Slack channel for this. As fallback, you can ask in #random

**Comment by OlafEichstaedt** [comment]
@sypets 

"I did step 1 first" => register for a Type3.org account

I just wanted to let you know that the documentation does no work as expected (you do step 1, you click step 2 and a 404 error occurs ...).
