### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#21]
https://docs.typo3.org/typo3cms/GettingStartedTutorial/NextSteps/Index.html

and subpages

**Comment by yurigoul** [comment]
For instance the page **Editors Tutorial** links to the French version at https://docs.typo3.org/typo3cms/EditorsTutorial/fr_FR/Index.html#start

I must say it is good to know the French version exists and it SHOULD be known that other language versions are there - but if you do not know French and changing the language info to another link does not produce any other language version, then this is not good.

The right link should be https://docs.typo3.org/typo3cms/EditorsTutorial/ since people come from the en_US version. Though it might be a good idea to move the en_US version of the tutorial to ttps://docs.typo3.org/typo3cms/EditorsTutorial/en_US/Index.html#start

**Comment by sypets** [comment]
@yurigoul Thanks. Where did you find the link to the french version? Please supply the URL to the page where the wrong link is on as well.

The French version doesn't really exist. The page https://docs.typo3.org/typo3cms/EditorsTutorial/fr_FR/Index.html#start does contain a start page in French but that's about it. I don't think this is maintained any longer, but that is a different topic. I will forward.
